### PR TITLE
Update plutono dashboard tags

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
The rsyslog dashboard tags were most likely copied from the registry-cache dashboard and we missed to update them:
Screenshot 2024-02-22 at 10 48 30

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by plkokanov** [comment]
I found one more similar occurrence in the `constants.go` file: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/a49fa6cf2e8e4701d5ed4e83e8bafe463269b71a/pkg/constants/constants.go#L14

**Comment by ialidzhikov** [comment]
> Could we also adapt it in this PR?

Sure, nice catch!

**Comment by plkokanov** [comment]
> @ialidzhikov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

This seems like a new flake or a reoccurrence of https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/26#issuecomment-1801968833 I will try to reproduce it locally and open an issue with what I find.

```
  [FAILED] Timed out after 20.001s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener-extension-shoot-rsyslog-relp/test/common/verifier.go:100 with:
  Expected the rsyslog.service unit to be active on node machine-shoot--local--e2e-rslog-hib-local-795b9-2nlkj
  Expected
      <string>: not active\n
  to equal
      <string>: active\n
  In [It] at: /home/prow/go/src/github.com/gardener/gardener-extension-shoot-rsyslog-relp/test/e2e/create_enabled_hibernate_reconcile_delete_test.go:51 @ 02/22/24 10:29:06.064
```

/test pull-gardener-extension-shoot-rsyslog-relp-e2e-kin

**Pull request merged**
