### PR TITLE
Move `images.yaml` file to dedicated `imagevector` package

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
This PR aligns the location of the `images.yaml` file with other `gardener` repositories. 

With this PR the `images.yaml` file is in a place that the [`set_dependency_version`](https://github.com/gardener/gardener/blob/master/hack/.ci/set_dependency_version) script expects (namely, [this code](https://github.com/gardener/gardener/blob/7333ea1baf753a9c1f40f9b68ce2907065e042a9/hack/.ci/set_dependency_version#L24-L28)).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I have to check if this  [`set_dependency_version`](https://github.com/gardener/gardener/blob/master/hack/.ci/set_dependency_version) script is actually necessary for the gardener-extension-shoot-rsyslog-relp repository. As far as I can see, it is not included in https://github.com/gardener/gardener-extension-registry-cache. If it is not needed, I can enhance this PR to remove that as well.

**Release note**:

```noteworthy developer
The `charts/images.yaml` file was moved to `imagevector/images.yaml`.
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
> I have to check if this [set_dependency_version](https://github.com/gardener/gardener/blob/master/hack/.ci/set_dependency_version) script is actually necessary for the gardener-extension-shoot-rsyslog-relp repository. As far as I can see, it is not included in https://github.com/gardener/gardener-extension-registry-cache. If it is not needed, I can enhance this PR to remove that as well.

Yes, I noticed that as well. I suggest to drop it, I don't see it being used.

**Comment by plkokanov** [comment]
/hold
We can merge this after https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/57 to not introduce any more rebase conflicts.

**Comment by plkokanov** [comment]
> Yes, I noticed that as well. I suggest to drop it, I don't see it being used.

Done

**Pull request merged**
